name: Build artifacts

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-artifacts-X64-Linux:
    runs-on: UbuntuLatest32Cores128G
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: DeterminateSystems/flake-checker-action@main

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build package
        run: "nix build .# -L --fallback && nix-store --export $(nix-store -qR ./result) | xz -9 > magic-nix-cache.closure.xz"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: magic-nix-cache-X64-Linux
          path: magic-nix-cache.closure.xz
          retention-days: 1
