name: Build artifacts

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-artifacts-macOS:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - uses: DeterminateSystems/nix-installer-action-cache@main

      - name: Build package
        run: "nix build .# -L"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: nix-actions-cache-macOS
          path: result/bin/nix-actions-cache
          retention-days: 1

  build-artifacts-Linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: DeterminateSystems/nix-installer-action-cache@main

      - name: Build package
        run: "nix build .# -L"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: nix-actions-cache-Linux
          path: result/bin/nix-actions-cache
          retention-days: 1
