name: Build artifacts

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-artifacts:
    runs-on: ${{ matrix.systems.runner }}
    permissions:
      contents: read
      id-token: write
    env:
      ARTIFACT_KEY: magic-nix-cache-${{ matrix.systems.system }}
      ARCHIVE_NAME: magic-nix-cache.closure.xz
    strategy:
      matrix:
        systems:
          - nix-system: aarch64-darwin
            system: ARM64-macOS
            runner: macos-latest-xlarge
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix on ${{ matrix.systems.system }}
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-args: "--determinate"
          flakehub: true
        #   extra-conf: "max-substitution-jobs = 8"
      - name: fixup dnixd launchd conf
        run: |
          nix profile install nixpkgs#gnused
          sudo launchctl limit maxfiles 9000000 9999999
          sudo $(which sed) -i 's/1048576/9999999/g' /Library/LaunchDaemons/systems.determinate.nix-daemon.plist
          sudo $(which sed) -i 's/2097152/9999999/g' /Library/LaunchDaemons/systems.determinate.nix-daemon.plist
          sudo launchctl kickstart -k system/systems.determinate.nix-daemon
      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build and cache dev shell for ${{ matrix.systems.nix-system }}
        run: |
          nix build ".#devShells.${{ matrix.systems.nix-system }}.default"

      - name: Build package and create closure for ${{ matrix.systems.system }}
        run: |
          nix build .# -L --fallback && \
            nix-store --export $(nix-store -qR ./result) | xz -9 > "${{ env.ARCHIVE_NAME }}"

      - name: Upload magic-nix-cache closure for ${{ matrix.systems.system }}
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: ${{ env.ARTIFACT_KEY }}
          path: ${{ env.ARCHIVE_NAME }}
          retention-days: 1
