name: Build artifacts

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build-artifacts-X64-macOS:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - uses: DeterminateSystems/flake-checker-action@v4

      - uses: DeterminateSystems/nix-installer-action@v4

      # - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build package
        run: "nix build .# -L"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: magic-nix-cache-X64-macOS
          path: result/bin/magic-nix-cache
          retention-days: 1

  build-artifacts-X64-Linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: DeterminateSystems/flake-checker-action@v4

      - uses: DeterminateSystems/nix-installer-action@v4

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build package
        run: "nix build .# -L"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: magic-nix-cache-X64-Linux
          path: result/bin/magic-nix-cache
          retention-days: 1
