name: Rust checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Check health of flake.lock
        uses: DeterminateSystems/flake-checker-action@v4
        with:
          fail-mode: true

      - uses: DeterminateSystems/magic-nix-cache@main

      - name: Check Rust formatting
        run: nix develop --command cargo fmt --check

      - name: Clippy
        run: nix develop --command cargo clippy
