name: Release Tags

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    permissions:
      contents: read
    uses: ./.github/workflows/build.yaml

  release:
    needs: build

    concurrency: release
    runs-on: ubuntu-latest
    permissions:
      contents: write # In order to upload artifacts to GitHub releases
      id-token: write # In order to request a JWT for AWS auth
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Create the artifacts directory
        run: rm -rf ./artifacts && mkdir ./artifacts

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: magic-nix-cache-ARM64-macOS
          path: cache-binary-ARM64-macOS
      - name: Persist the cache binary
        run: cp ./cache-binary-ARM64-macOS/magic-nix-cache.closure.xz ./artifacts/ARM64-macOS

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: magic-nix-cache-X64-Linux
          path: cache-binary-X64-Linux
      - name: Persist the cache binary
        run: cp ./cache-binary-X64-Linux/magic-nix-cache.closure.xz ./artifacts/X64-Linux

      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: magic-nix-cache-ARM64-Linux
          path: cache-binary-ARM64-Linux
      - name: Persist the cache binary
        run: cp ./cache-binary-ARM64-Linux/magic-nix-cache.closure.xz ./artifacts/ARM64-Linux

      - uses: DeterminateSystems/push-artifact-ids@main
        with:
          s3_upload_role: ${{ secrets.AWS_S3_UPLOAD_ROLE }}
          bucket: ${{ secrets.AWS_S3_UPLOAD_BUCKET }}
          directory: ./artifacts
          ids_project_name: magic-nix-cache
          ids_binary_prefix: magic-nix-cache

      - name: Rename binaries for GH release
        run: |
          mv ./artifacts/{,magic-nix-cache-closure-}ARM64-macOS
          mv ./artifacts/{,magic-nix-cache-closure-}X64-Linux
          mv ./artifacts/{,magic-nix-cache-closure-}ARM64-Linux

      - name: Publish Release to GitHub (Tag)
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0 # zizmor: ignore[superfluous-actions]
        with:
          fail_on_unmatched_files: true
          draft: true
          files: |
            artifacts/**
